image:
  repository: synology/synology-csi
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130

synology:
  host: ""
  port: 5000
  ssl: false
  adminUsername: ""
  adminPassword: ""

chap:
  enabled: true

serviceAccount:
  create: true
  name: gardener-extension-csi-driver-synology

rbac:
  create: true
